version: '3'
services:
  edomi:
    environment:
    - WEBSOCKETPORT=8081
    ports:
    - 81:80/tcp
    - 8081:8081/tcp
    - 3671:3671/tcp
    - 50000:50000/udp
    - 50001:50001/udp
    - 22222:22/udp  
    container_name: edomi
    image: starwarsfan/edomi-docker:amd64-latest
    network_mode: "bridge"
    restart: on-failure