version: '3'
services:
  edomi:
    container_name: edomi
    image: starwarsfan/edomi-docker:amd64-latest
    ports:
      - 81:80/tcp
      - 8081:8081/tcp
      - 3671:3671/tcp
      - 50000:50000/udp
      - 50001:50001/udp
      - 22222:22/udp
    network_mode: "host"
    restart: always